# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d94bf4314276f03c85f493999ed9086c8cdfffb7647123bfc4096026474b6595f63752669ac2618a4ec5dab2e7c2b7c4d80ceb34c36f638260c1bcbbad477db

test:
  secret_key_base: 7b072b5333521b708d5fb7ba19783605d5d7a74311b0adac2211405c462c406f89704f747bb1a852afd4d153d05a6c30fc17cc03466415fc46a7c41061ef9038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
